<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<AssetBundlePath>UnityProject - PlateupAP\content\mod.assets</AssetBundlePath>
		<LangVersion>8.0</LangVersion>
		<IsPacked>true</IsPacked>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ILRepack" Version="2.0.46">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.46">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Yariazen.PlateUp.ModBuildUtilities" Version="1.13.0" />
		<PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.1" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="UnityProject - PlateupAP\**" />
		<None Remove="UnityProject - PlateupAP\**" />
	</ItemGroup>

	<ItemGroup>
		<Folder Condition="Exists('Changelogs')" Include="Changelogs\" />
		<Folder Condition="Exists('Changelogs\Github')" Include="Changelogs\Github" />
		<Folder Condition="Exists('Changelogs\Workshop')" Include="Changelogs\Workshop" />
		<Folder Include="Properties\" />
	</ItemGroup>
</Project>
